[package]
name = "statusbar"
version = "0.1.0"
authors = ["Noam Kadosh <noamkadosh91@gmail.com>", "Alex Fedoseev <alex@fedoseev.mx>"]
edition = "2021"

[dependencies]
zellij-tile = "0.40.1"
zellij-tile-utils = "0.40.1"
chrono = "0.4.42"
colored = "3"
ansi_term = "0.12.1"
unicode-width = "0.2.1"
